#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if command_exists "./vendor/bin/duster fix"; then
    echo "🔍 Running Duster Fix..."
    ./vendor/bin/duster fix || display_error "Duster found issues"
fi
